vich_uploader:
    db_driver: orm # which persistence engine to use

    mappings:
        photos:
            uri_prefix: /auctions/photos
            upload_destination: '%kernel.project_dir%/public/auctions/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer