vich_uploader:
    db_driver: orm # which persistence engine to use

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
